### ISSUE TITLE
Voice to  text convertion not working 

### ISSUE THREAD

**Issue by chappanagavendra** [api-ai/api-ai-ios-sdk#19]
Hi .. 

i run the sample code  with my client token ... text request working good but speech to text giving **"Error Domain=NSURLErrorDomain Code=-1017 "cannot parse response" UserInfo=0x1700f3700 {NSUnderlyingError=0x17004efd0 "The operation couldn’t be completed. (kCFErrorDomainCFNetwork error -1017.)", NSErrorFailingURLStringKey=https://api.api.ai/v1/query%3Fv=20150910, NSErrorFailingURLKey=https://api.api.ai/v1/query%3Fv=20150910, _kCFStreamErrorDomainKey=4, _kCFStreamErrorCodeKey=-1, NSLocalizedDescription=cannot parse response}
"**

**Some times :-  Error code 403 , Api.Ai speech recognition is going to deprecated soon.**

Note :-  Xcode 7.1 .. checking in iPad Air 8.0

Please help me ...  Thanks in advance

**Comment by sstepashka** [comment]
Hi @chappanagavendra,

Our company's main focus is NLU (natural language understanding) and dialog management. We provide a platform for creating conversational interfaces (called agents) for apps, bots, and devices. These interfaces are designed to receive text as input information.

Depending on your app, bot, or device platform, speech recognition might be available natively. For example, if you are building an Action on Google, Google Home supports speech recognition natively.

For some other platforms, speech recognition can be integrated as an additional component. 

API.AI doesn't provide speech recognition services. You can consider using Google Speech API or other 3rd party solution for speech recognition and use API.AI for building a conversational interface.

Let me know if you have any questions.

Regards,
Dmitriy

**Comment by Tidrek** [comment]
@sstepashka 
Dear Dmitriy
This is just so sad and such a nonsense. It's one of killer-features of api.ai: one web request to make speech recognition and NLU. As far as I know, nobody else does it! Api.ai is a Google company, why not make an integration with their Speech API? Now since you guys decided to remove it from your platform, users have to make two web requests: one for speech recognition and the other for NLU to gain the same result. This is a significant responsiveness loss. I'm afraid with these conditions, I have to use something else because making users wait for ~6 seconds for their every voice action is not tolerable.

Is there any way you can change your plans just a tiny bit? Can I submit a feature request, or maybe you can raise this issue among your team members?

**Comment by DheerajAluru** [comment]
Hi...Can anyone help me with the integration of cloud speech API to dialogflow?
Please help me..Thanks in advance.
